package com.cibeg.esb.wsvc.v5_0.correspondence;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-07-17T18:01:46.928+02:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "ESB_Correspondence",
                  wsdlLocation = "file:/C:/Users/ESMO40210/Desktop/sendsms/src/main/resources/correspondence_v5.0.wsdl",
                  targetNamespace = "http://www.cibeg.com/esb/wsvc/v5.0/correspondence/")
public class ESBCorrespondence_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cibeg.com/esb/wsvc/v5.0/correspondence/", "ESB_Correspondence");
    public final static QName Correspondence12 = new QName("http://www.cibeg.com/esb/wsvc/v5.0/correspondence/", "Correspondence12");
    public final static QName Correspondence11 = new QName("http://www.cibeg.com/esb/wsvc/v5.0/correspondence/", "Correspondence11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/ESMO40210/Desktop/sendsms/src/main/resources/correspondence_v5.0.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ESBCorrespondence_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ESMO40210/Desktop/sendsms/src/main/resources/correspondence_v5.0.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ESBCorrespondence_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ESBCorrespondence_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ESBCorrespondence_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ESBCorrespondence_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ESBCorrespondence_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ESBCorrespondence_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ESBCorrespondence
     */
    @WebEndpoint(name = "Correspondence12")
    public ESBCorrespondence getCorrespondence12() {
        return super.getPort(Correspondence12, ESBCorrespondence.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ESBCorrespondence
     */
    @WebEndpoint(name = "Correspondence12")
    public ESBCorrespondence getCorrespondence12(WebServiceFeature... features) {
        return super.getPort(Correspondence12, ESBCorrespondence.class, features);
    }


    /**
     *
     * @return
     *     returns ESBCorrespondence
     */
    @WebEndpoint(name = "Correspondence11")
    public ESBCorrespondence getCorrespondence11() {
        return super.getPort(Correspondence11, ESBCorrespondence.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ESBCorrespondence
     */
    @WebEndpoint(name = "Correspondence11")
    public ESBCorrespondence getCorrespondence11(WebServiceFeature... features) {
        return super.getPort(Correspondence11, ESBCorrespondence.class, features);
    }

}
